VeterinarskaStanica.Web/Controllers/TerminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using VeterinarskaStanica.BLL;
using VeterinarskaStanica.DAL.Repository;
using VeterinarskaStanica.Model;

namespace VeterinarskaStanica.Web.Controllers
{

    public class TerminController : Controller
    {
        // GET: Termin
        // Zatrazeni termini
        [Authorize]
        public ActionResult Index()
        {
            VlasnikService VlasnikService = new VlasnikService();
            string KorisnickoIme = User.Identity.Name;
            var Vlasik = VlasnikService.GetIdByKorisnickoIme(KorisnickoIme);

            var TerminService = new TerminService();
            var Termini = TerminService.GetAllByVlasnikId(Vlasik.Id);
            return View(Termini);
        }
        [Authorize]
        public ActionResult Zatrazeni()
        {
            VlasnikService VlasnikService = new VlasnikService();
            string KorisnickoIme = User.Identity.Name;
            var Vlasik = VlasnikService.GetIdByKorisnickoIme(KorisnickoIme);

            var TerminService = new TerminService();
            var Termini = TerminService.GetAllZatrazeniByVlasnikId(Vlasik.Id);
            return View(Termini);
        }
        [Authorize]
        public ActionResult Odobreni()
        {
            VlasnikService VlasnikService = new VlasnikService();
            string KorisnickoIme = User.Identity.Name;
            var Vlasik = VlasnikService.GetIdByKorisnickoIme(KorisnickoIme);

            var TerminService = new TerminService();
            var Termini = TerminService.GetAllOdobreniByVlasnikId(Vlasik.Id);
            return View(Termini);
        }
        // GET: Termin/Details/5
        [Authorize]
        public ActionResult Otkazi(int id)
        {
            var TerminService = new TerminService();
            Termin Termin = TerminService.GetById(id);
            Termin.Status = StatusTermina.Otkazan;
            TerminService.Update(Termin);
            return RedirectToAction("Index"); ;
        }

        // GET: Termin/Details/5
        [Authorize]
        public ActionResult Details(int id)
        {
            TerminService TerminService = new TerminService();
            Termin Termin = TerminService.GetById(id);
            return View(Termin);
        }

        // GET: Termin/Create
        [Authorize]
        public ActionResult Create(int id)
        {
            TerminService TerminService = new TerminService();
            ViewBag.IdVrstaTermina = new SelectList(TerminService.GetAllVrstaTermina(), "Id", "Naziv");
            ViewBag.IdZivotinje = id;
            return View();
        }

        // POST: Termin/Create
        [HttpPost]
        [Authorize]
        public ActionResult Create([Bind(Include = "Datum,Iskaz,Napomena,Opis,VrstaTermina_Id")] Termin Termin, int IdZivotinje)
        {

            try
            {
                var IdVrstaTermina = int.Parse(Request.Form.GetValues("IdVrstaTermina")[0]);
                TerminService TerminService = new TerminService();
                Termin.VrstaTermina = TerminService.GetVrstaTerminaById(IdVrstaTermina);

                ZivotinjaService ZivotinjaService = new ZivotinjaService();
                Termin.Zivotinja= ZivotinjaService.GetById(IdZivotinje);
                Termin.Status = StatusTermina.Zatražen;

                TerminService.Add(Termin);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Termin/Edit/5
        [Authorize]
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Termin/Edit/5
        [HttpPost]
        [Authorize]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Termin/Delete/5
        [Authorize]
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Termin/Delete/5
        [HttpPost]
        [Authorize]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here
                TerminService TerminService = new TerminService();
                TerminService.Delete(id);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

VeterinarskaStanica.Web/Controllers/ZivotinjaController.cs
using NHibernate;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using VeterinarskaStanica.BLL;
using VeterinarskaStanica.DAL;
using VeterinarskaStanica.DAL.Repository;
using VeterinarskaStanica.Model;
using VeterinarskaStanica.Web.Models;

namespace VeterinarskaStanica.Web.Controllers
{
    public class ZivotinjaController : Controller
    {
        // GET: Zivotinja
        [Authorize]
        public ActionResult Index()
        {
            VlasnikService VlasnikService = new VlasnikService();
            string KorisnickoIme = User.Identity.Name;
            var Vlasik = VlasnikService.GetIdByKorisnickoIme(KorisnickoIme);


            var ZivotinjaService = new ZivotinjaService();
            var zivotinje = ZivotinjaService.GetAllByVlasnikId(Vlasik.Id);
            return View(zivotinje);
        }

        // GET: Zivotinja
        [Authorize]
        [HttpPost]
        public ActionResult GetPasmineByIdVrsta(int id)
        {
            var service = new ZivotinjaService();
            var pasmine = service.GetPasmineByIdVrsta(id);
                
            var json= Json(pasmine);
            return json;
        }
        
        // GET: Zivotinja/Details/5
        [Authorize]
        public ActionResult Details(int id)
        {
            var service = new ZivotinjaService();
            var zivotinja = service.GetById(id);

            TerminService TerminService = new TerminService();
            ViewBag.Termini = TerminService.GetAllByIdZivotinja(zivotinja.Id);
            return View(zivotinja);
        }

        // GET: Zivotinja/Create
        [Authorize]
        public ActionResult Create()
        {

            ZivotinjaService zr = new ZivotinjaService();
            

            ViewBag.IdVrstaZivotinje = new SelectList(zr.GetAllVrstaZivotinje(), "Id", "Naziv");
            ViewBag.IdPasminaZivotinje = new SelectList(zr.GetAllPasminaZivotinjeByVrstaZivotinje(zr.GetAllVrstaZivotinje()[0]), "Id", "Naziv");
            ViewBag.Spol= new SelectList(Enum.GetValues(typeof(Spol)));
            return View();
        }

        // POST: Zivotinja/Create
        [HttpPost]
        [Authorize]
        public ActionResult Create([Bind(Include = "Ime,Spol,DatumRodenja,DatumSmrti,Boja,BrojCipa,PolozajCipa,DatumCipiranja")] Zivotinja Zivotinja, HttpPostedFileBase file)
        {
            var service = new ZivotinjaService();
            VlasnikService VlasnikService = new VlasnikService();
            string KorisnickoIme = User.Identity.Name;
            var Vlasnik = VlasnikService.GetIdByKorisnickoIme(KorisnickoIme);
            Zivotinja.Vlasnik = Vlasnik;
            var IdVrstaZivotinje = int.Parse(Request.Form.GetValues("IdVrstaZivotinje")[0]);
            var IdPasminaZivotinje = int.Parse(Request.Form.GetValues("IdPasminaZivotinje")[0]);

            ZivotinjaService ZivotinjaService = new ZivotinjaService();
            Zivotinja.VrstaZivotinje = ZivotinjaService.GetVrstaZivotinjeById(IdVrstaZivotinje);
            Zivotinja.PasminaZivotinje = ZivotinjaService.GetPasminaZivotinjeById(IdPasminaZivotinje);
            var zivotinje = service.Add(Zivotinja);
            return RedirectToAction("Index");
            //ovo dolje je bio pokusaj dokumenata
            try
            {

                
                
                if (file.ContentLength > 0)
                {
                    var fileName = Path.GetFileName(file.FileName);
                    var path = Path.Combine(Server.MapPath("~/App_Data/uploads"), fileName);
                    file.SaveAs(path);
                }
                //var IdVrstaZivotinje = int.Parse(Request.Form.GetValues("IdVrstaZivotinje")[0]);
                //var IdPasminaZivotinje = int.Parse(Request.Form.GetValues("IdPasminaZivotinje")[0]);
                //ZivotinjaRepository ZivotinjaRepository = new ZivotinjaRepository();
                //Zivotinja.VrstaZivotinje = ZivotinjaRepository.GetVrstaZivotinjeById(IdVrstaZivotinje);
                //Zivotinja.PasminaZivotinje = ZivotinjaRepository.GetPasminaZivotinjeById(IdPasminaZivotinje);
                //var service = new ZivotinjaService();
                //var zivotinje = service.Add(Zivotinja);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Zivotinja/Edit/5
        [Authorize]
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Zivotinja/Edit/5
        [HttpPost]
        [Authorize]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Zivotinja/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Zivotinja/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                var service = new ZivotinjaService();
                var zivotinje = service.Delete(id);

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

VeterinarskaStanica.Web/Views/Zivotinja/Create.cshtml
@model VeterinarskaStanica.Model.Zivotinja
@{
    ViewBag.Title = "Dodaj novu životinju";
}

<h2>Dodaj novu životinju</h2>


<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" type="text/javascript"></script>


<script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8/jquery-ui.min.js"></script>
<script language="javascript" type="text/javascript">
    function GetPasmine(id) {
        
        var procemessage = "<option value='0'> Please wait...</option>";
        $("#ddlcity").html(procemessage).show();
        var url = "/Zivotinja/GetPasmineByIdVrsta/"+id;

        $.ajax({
            url: url,
            data: { id: id },
            cache: false,
            type: "POST",
            success: function (data) {
                
                var markup = "<option value='0'>Izaberi pasminu</option>";
                for (var x = 0; x < data.length; x++) {
                    
                    markup += "<option value=" + data[x].Id + ">" + data[x].Naziv + "</option>";
                }
                $("#IdPAsminaZivotinje").html(markup).show();
            },
            error: function (reponse) {
                
                alert("Nije uspio dohvat : " + JSON.parse(reponse));
            }
        });

    }
</script>





@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Životinja</h4>
        <hr />
        @Html.ValidationSummary(false, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Ime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Ime, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Ime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DatumRodenja, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DatumRodenja, new { htmlAttributes = new { @class = "form-control" } })
                @*@Html.ValidationMessageFor(model => model.DatumRodenja, "", new { @class = "text-danger" })*@
            </div>
        </div>



        <div class="form-group">
            @Html.LabelFor(model => model.Boja, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Boja, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Boja, "", new { @class = "text-danger" })
            </div>
        </div>



        <div class="form-group">
            @Html.LabelFor(model => model.Spol, "Spol", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Spol", null, htmlAttributes: new { @class = "form-control" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.VrstaZivotinje, "Vrsta životinje", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("IdVrstaZivotinje", null, htmlAttributes: new { @class = "form-control", @onchange = "javascript:GetPasmine(this.value);" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.PasminaZivotinje, "PAsmina životinje", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("IdPAsminaZivotinje", null, htmlAttributes: new { @class = "form-control" })

            </div>
        </div>

        @*<div class="form-group">
            @Html.LabelFor(model => model.Dokumenti, "Dokumenti", htmlAttributes: new { @class = "control-label col-md-2", @onchange = "javascript:alert();" })

            <div class="col-md-10">
                <InPUT type=file multiple=multiple id=File1 name=File1 runat=server />
            </div>


        </div>*@
        @*<div class="form-group">
            @Html.DropDownListFor(model => model.VrstaZivotinje, new SelectList(ViewBag.IdVrstaZivotinje, "IdVrstaZivotinje"), new { @id = "ddlstate", @style = "width:200px;", @onchange = "javascript:GetCity(this.value);" })
            <br />
            <br />
            <select id="ddlcity" name="ddlcity" style="width: 200px"></select>

            <br /><br />

        </div>*@


        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Spremi" enctype="multipart/form-data" class="btn btn-default"   />
            </div>
        </div>
    </div>

}

<div>
    @Html.ActionLink("Vrati se na listu", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}
@using (Html.BeginForm("FolderChange", "ControllerName", FormMethod.Post, new { id = "ediFilesForm" }))
{
    ////your code
}

VeterinarskaStanica.Web/Views/Zivotinja/Delete.cshtml
@model VeterinarskaStanica.Model.Zivotinja

@{
    ViewBag.Title = "ZivotinjaDelete";
}

<h2>ZivotinjaDelete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Zivotinja</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Ime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DatumRodenja)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DatumRodenja)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DatumSmrti)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DatumSmrti)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Boja)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Boja)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BrojCipa)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BrojCipa)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PolozajCipa)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PolozajCipa)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DatumCipiranja)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DatumCipiranja)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

VeterinarskaStanica.Web/Views/Zivotinja/Details.cshtml
@model VeterinarskaStanica.Model.Zivotinja
@using VeterinarskaStanica.Model
@{
    ViewBag.Title = "Detalji životinje";
    
}

<h2>Detalji životinje</h2>

<div>
    <h4>Zivotinja</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Ime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.VrstaZivotinje.Naziv)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.VrstaZivotinje.Naziv)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PasminaZivotinje.Naziv)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PasminaZivotinje.Naziv)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DatumRodenja)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DatumRodenja)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DatumSmrti)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DatumSmrti)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Boja)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Boja)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BrojCipa)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BrojCipa)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PolozajCipa)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PolozajCipa)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DatumCipiranja)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DatumCipiranja)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Vrati se na listu", "Index")
</p>





@*Termini*@



<h2>Termini</h2>
<table class="table">
    <tr>
        <th>
            @Html.DisplayName("Datum")
        </th>
        <th>
            @Html.DisplayName("Vrsta termina")
        </th>
        <th>
            @Html.DisplayName("Status termina")
        </th>
        <th>
            @Html.DisplayName("Napomena")
        </th>

        <th></th>
    </tr>

    @foreach (var item in (List<Termin>)ViewBag.Termini)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Datum)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.VrstaTermina.Naziv)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Status)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Napomena)
            </td>

            <td>
                @Html.ActionLink("Detalji", "Details","Termin", new { id = item.Id }, null)
            </td>
        </tr>
    }

</table>

VeterinarskaStanica.Web/Views/Zivotinja/Edit.cshtml
@model VeterinarskaStanica.Model.Zivotinja

@{
    ViewBag.Title = "ZivotinjaEdit";
}

<h2>ZivotinjaEdit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Zivotinja</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Ime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Ime, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Ime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DatumRodenja, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DatumRodenja, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DatumRodenja, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DatumSmrti, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DatumSmrti, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DatumSmrti, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Boja, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Boja, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Boja, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BrojCipa, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BrojCipa, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BrojCipa, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PolozajCipa, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PolozajCipa, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PolozajCipa, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DatumCipiranja, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DatumCipiranja, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DatumCipiranja, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

VeterinarskaStanica.Web/Views/Zivotinja/Index.cshtml
@model IEnumerable<VeterinarskaStanica.Model.Zivotinja>

@{
    ViewBag.Title = "Moje životinje";
}

<h2>Moje životinje</h2>

<p>
    @Html.ActionLink("Dodaj novu životinju", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Ime)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.VrstaZivotinje.Naziv)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Spol)
        </th>
 
        <th>
            @Html.DisplayNameFor(model => model.Boja)
        </th>
 
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr onclick="location.href = '@(Url.Action("Details", "Zivotinja", new { id = item.Id }))'" class="zivotinjeCursor">
        <td>
            @Html.DisplayFor(modelItem => item.Ime)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.VrstaZivotinje.Naziv)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Spol)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Boja)
        </td>
        
        
        
        <td>
            @Html.ActionLink("Detalji", "Details", new { id=item.Id }) |
            @Html.ActionLink("Zatraži termin za životinju", "Create", "Termin", new { id = item.Id }, htmlAttributes: new { id = item.Id })
        </td>
    </tr>
}

</table>

VeterinarskaStanica.Web/Views/Zivotinja/View.cshtml
@model VeterinarskaStanica.Web.Models.UploadForm

@{
    ViewBag.Title = "View";
}

<h2>View</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>UploadForm</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

VeterinarskaStanica.Web/Views/Zivotinja/ZivotinjaDelete.cshtml
@model VeterinarskaStanica.Model.Zivotinja

@{
    ViewBag.Title = "ZivotinjaDelete";
}

<h2>ZivotinjaDelete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Zivotinja</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Ime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DatumRodenja)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DatumRodenja)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DatumSmrti)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DatumSmrti)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Boja)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Boja)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BrojCipa)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BrojCipa)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PolozajCipa)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PolozajCipa)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DatumCipiranja)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DatumCipiranja)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>